Advanced operations

In [1]:
import numpy as np

Sales example

In [5]:
sales_data = np.array([
    [1,12,23,34,45],
    [2,13,24,35,46],
    [3,14,25,36,47],
    [4,15,26,37,48],
    [5,16,27,38,49]
])

print("================  Sales Data  ================")
print("\n Sales Data Shape : ", sales_data.shape)
print("\n Sales Data for 1st 3 restaurants : \n", sales_data[:3])
print("\n Sales Data for 3rd 2 restaurants : \n", sales_data[2:4])
print("\n Sales Data custom index : \n", sales_data[:, 1:3])



================  Sales Data  ================

 Sales Data Shape :  (5, 5)

 Sales Data for 1st 3 restaurants : 
 [[ 1 12 23 34 45]
 [ 2 13 24 35 46]
 [ 3 14 25 36 47]]

 Sales Data for 3rd 2 restaurants : 
 [[ 3 14 25 36 47]
 [ 4 15 26 37 48]]

 Sales Data custom index : 
 [[12 23]
 [13 24]
 [14 25]
 [15 26]
 [16 27]]
