## Learn about numpy

Creating array using list

In [ ]:
import numpy as np

arr_1d = np.array([1,2,3])
arr_2d = np.array([[1,2,3],[4,5,6]])
arr_3d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(arr_1d)
print(arr_2d)
print(arr_3d)



[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


Some Multiplication

In [1]:
import numpy as np

py_list = [1,2,3]

print("python list multiply ", py_list * 3)

np_arr = np.array([1,2,3])

print("numpy array multiply ", np_arr * 3)

python list multiply  [1, 2, 3, 1, 2, 3, 1, 2, 3]
numpy array multiply  [3 6 9]


List and array

In [1]:
import numpy as np
import time

start = time.time()

py_list = [i*3 for i in range(1000000)]
print("\nList time: ",time.time() - start)

start = time.time()
np_arr = np.array([i*2 for i in range(1000000)])
print("\nArray time: ",time.time() - start)


List time:  0.03513765335083008

Array time:  0.06951713562011719


creating arrays

In [21]:
import numpy as np

# Zeros array

zeros = np.zeros((2,4))
print("zeros array : \n" , zeros)

# ones array

ones = np.ones((2,4))
print("ones array : \n" , ones)

# Special constant array

full = np.full((2,4), 15)
print("full array : \n" , full)

# Random array random have many methods

random = np.random.random((2,4))
print("random array : \n" , random *3)

# sequence array

seq = np.arange(0,100,5)
print("sequence array : \n" , seq)

zeros array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array : 
 [[15 15 15 15]
 [15 15 15 15]]
random array : 
 [[2.04808973 2.94590118 2.27621495 1.37096399]
 [1.18105404 0.54502673 1.38461199 1.3653666 ]]
sequence array : 
 [ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


Vector , Matrix and Tensor

In [ ]:
import numpy as np

vector = np.array([1,2,3,4,5,6,7,8])
print(vector) # 1D array

matrix = np.array([[1,2,3],[1,2,3]])
print(matrix) # 2D array

tensor = np.array([[[1,2,3],[1,2,3]], [[1,2,3], [1,2,3]]])
print(tensor) # 3D and higher array

[1 2 3 4 5 6 7 8]
[[1 2 3]
 [1 2 3]]
[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]
