## Learn about numpy

Creating array using list

In [3]:
import numpy as np

arr_1d = np.array([1,2,3])
arr_2d = np.array([[1,2,3],[4,5,6]])
arr_3d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(arr_1d)
print(arr_2d)
print(arr_3d)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
