Advanced operations

In [1]:
import numpy as np

Sales example

In [ ]:
sales_data = np.array([
    [1,12,23,34,45],
    [2,13,24,35,46],
    [3,14,25,36,47],
    [4,15,26,37,48],
    [5,16,27,38,49]
])

print("================  Sales Data  ================")
print("\n Sales Data Shape : ", sales_data.shape)
print("\n Sales Data for 1st 3 restaurants : \n", sales_data[:3])
print("\n Sales Data for 3rd 2 restaurants : \n", sales_data[2:4])
print("\n Sales Data custom index : \n", sales_data[:, 1:3])



================  Sales Data  ================

 Sales Data Shape :  (5, 5)

 Sales Data for 1st 3 restaurants : 
 [[ 1 12 23 34 45]
 [ 2 13 24 35 46]
 [ 3 14 25 36 47]]

 Sales Data for 3rd 2 restaurants : 
 [[ 3 14 25 36 47]
 [ 4 15 26 37 48]]

 Sales Data custom index : 
 [[12 23]
 [13 24]
 [14 25]
 [15 26]
 [16 27]]


Total sales

In [ ]:
print(np.sum(sales_data, axis=0))  # col wise sum of sales data
print(np.sum(sales_data, axis=1))  # row wise sum of sales data
print("yearly sales for all restaurants : ", np.sum(sales_data[:,1:], axis=0))

print("\n Minimum sales for all restaurants : ", np.min(sales_data[:,1:], axis=0)) # col wise min
print("\n Maximum sales for all restaurants : ", np.max(sales_data[:,1:], axis=0)) # col wise max
print("\n Average sales for all restaurants : ", np.mean(sales_data[:,1:], axis=0)) # col wise avg
print("\n Standard Deviation for all restaurants : ", np.std(sales_data[:,1:], axis=0)) # col wise std

[ 15  70 125 180 235]
[115 120 125 130 135]
yearly sales for all restaurants :  [ 70 125 180 235]

 Minimum sales for all restaurants :  [12 23 34 45]

 Maximum sales for all restaurants :  [16 27 38 49]

 Average sales for all restaurants :  [14. 25. 36. 47.]

 Standard Deviation for all restaurants :  [1.41421356 1.41421356 1.41421356 1.41421356]
