Numpy Array Operations

In [2]:
import numpy as np

In [3]:
# 1D array operations

vector = np.array([1,2,3,4,5,6,7,8])
print("Slicing :", vector[3:6])
print("With Steps :", vector[1:5:2])
print("Negative Indexing :", vector[-1])

Slicing : [4 5 6]
With Steps : [2 4]
Negative Indexing : 8


Matrix Operations

In [4]:
matrix = np.array([[1,2,3],[1,2,3],[1,2,3]])

print("Specific element :", matrix[1,2])
print("Specific row :", matrix[1])
print("Specific column :", matrix[:,1])
print("Diagonal elements :", matrix.diagonal())

Specific element : 3
Specific row : [1 2 3]
Specific column : [2 2 2]
Diagonal elements : [1 2 3]


Sorting

In [6]:
unsorted = np.array([1,4,2,1,5,6,7,8])

print("Sorted array :", np.sort(unsorted))
print("Descending order :", np.sort(unsorted)[::-1])

arr_2d_unsorted = np.array([[1,4,2],[1,5,6],[7,8,9]])
print("Sorted 2D array :", np.sort(arr_2d_unsorted, axis=0))
print("Descending order 2D array :", np.sort(arr_2d_unsorted)[::-1])

Sorted array : [1 1 2 4 5 6 7 8]
Descending order : [8 7 6 5 4 2 1 1]
Sorted 2D array : [[1 4 2]
 [1 5 6]
 [7 8 9]]
Descending order 2D array : [[7 8 9]
 [1 5 6]
 [1 2 4]]


Filtering

In [10]:
arr = np.array([1,2,3,4,5,6,7,8])

even_number = arr[arr%2==0]
print("Even numbers :", even_number)

odd_number = arr[arr%2!=0]
print("Odd numbers :", odd_number)

Even numbers : [2 4 6 8]
Odd numbers : [1 3 5 7]


Filter with mask

In [ ]:
import time
start = time.time()

mask_arr = np.array([1,2,3,4,5,6,7,8,9,10])

mask = mask_arr > 7

print("Filtered array :", mask_arr[mask])

Filtered array : [ 8  9 10] 9.131431579589844e-05
