1. Import the numpy package under the name np.

In [1]:
import numpy as np

2. Print the numpy version and the configuration

In [4]:
print(np.__version__)
print(np.show_config())

2.3.2
{
  "Compilers": {
    "c": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "14.2.1",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.1.2",
      "commands": "cython"
    },
    "c++": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "14.2.1",
      "commands": "c++"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.30",
      "detection method": "pkgconfig",
      "include directory": "/opt/_internal/cpython-3.12.11/lib/python3.12/site-packages/scipy_openblas64/include",
      "lib directory": "/opt/_internal/cpython-3.12.11/lib/python3

/home/kunal/Desktop/Numpy/myenv/lib/python3.12/site-packages/numpy/__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


3. Create a null vector of size 10

In [10]:
# 10 elements with 0
vector = np.zeros(10)
print(vector)

# 20 elements with 1
vector = np.ones(20)
print(vector)

# 20 elements with 20
vector = np.full(10, 20)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[20 20 20 20 20 20 20 20 20 20]


4. How to find the memory size of any array

In [12]:
vector = np.arange(10, 50)
print(vector)
print("Vector memory size : ", vector.itemsize)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Vector memory size :  8


5. How to get the documentation of the numpy add function from the command line?

In [ ]:
# docs for numpy 
help(np.add) 

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

6. Create a null vector of size 10 but the fifth value which is 1

In [16]:
arr = np.zeros(10,dtype=int)
arr[4] = 1
print("Array : ",arr)

Array :  [0 0 0 0 1 0 0 0 0 0]


7. Create a vector with values ranging from 10 to 49

In [18]:
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Reverse a vector (first element becomes last)

In [24]:
vector = np.arange(10,20)
print(vector)
vector = vector[::-1]
print(vector)

[10 11 12 13 14 15 16 17 18 19]
[19 18 17 16 15 14 13 12 11 10]


9. Create a 3x3 matrix with values ranging from 0 to 8

In [31]:
matrix = np.arange(12).reshape(4,3)
print(matrix)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
