1. Import the numpy package under the name np.

In [2]:
import numpy as np

2. Print the numpy version and the configuration

In [4]:
print(np.__version__)
print(np.show_config())

2.3.2
{
  "Compilers": {
    "c": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "14.2.1",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.1.2",
      "commands": "cython"
    },
    "c++": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "14.2.1",
      "commands": "c++"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.30",
      "detection method": "pkgconfig",
      "include directory": "/opt/_internal/cpython-3.12.11/lib/python3.12/site-packages/scipy_openblas64/include",
      "lib directory": "/opt/_internal/cpython-3.12.11/lib/python3

/home/kunal/Desktop/Numpy/myenv/lib/python3.12/site-packages/numpy/__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


3. Create a null vector of size 10

In [10]:
# 10 elements with 0
vector = np.zeros(10)
print(vector)

# 20 elements with 1
vector = np.ones(20)
print(vector)

# 20 elements with 20
vector = np.full(10, 20)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[20 20 20 20 20 20 20 20 20 20]


4. How to find the memory size of any array

In [12]:
vector = np.arange(10, 50)
print(vector)
print("Vector memory size : ", vector.itemsize)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Vector memory size :  8


5. How to get the documentation of the numpy add function from the command line?

In [ ]:
# docs for numpy 
help(np.add) 

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

6. Create a null vector of size 10 but the fifth value which is 1

In [16]:
arr = np.zeros(10,dtype=int)
arr[4] = 1
print("Array : ",arr)

Array :  [0 0 0 0 1 0 0 0 0 0]


7. Create a vector with values ranging from 10 to 49

In [18]:
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Reverse a vector (first element becomes last)

In [24]:
vector = np.arange(10,20)
print(vector)
vector = vector[::-1]
print(vector)

[10 11 12 13 14 15 16 17 18 19]
[19 18 17 16 15 14 13 12 11 10]


9. Create a 3x3 matrix with values ranging from 0 to 8

In [31]:
matrix = np.arange(12).reshape(4,3)
print(matrix)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [32]:
arr = np.array([1,2,0,0,4,0])
print(arr)
print(np.nonzero(arr))

[1 2 0 0 4 0]
(array([0, 1, 4]),)


11. Create a 3x3 identity matrix

In [ ]:
matrix = np.eye(3)
print(matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


12. Create a 3x3x3 array with random values

In [5]:
ran_arr = np.random.random((3,3,3))
print(ran_arr)

[[[0.34192379 0.70982826 0.93962567]
  [0.64293604 0.91644793 0.12228777]
  [0.95189385 0.34285058 0.97271604]]

 [[0.90840344 0.12513751 0.73616129]
  [0.72926853 0.86139221 0.53610127]
  [0.7667185  0.97289112 0.29960344]]

 [[0.61163974 0.64376444 0.05129807]
  [0.82704547 0.72638355 0.04617076]
  [0.52989675 0.87397564 0.44490194]]]


13. Create a 10x10 array with random values and find the minimum and maximum values 

In [8]:
ran_arr = np.random.random((10,10))
print(ran_arr)

print(ran_arr.min())
print(ran_arr.max())

[[0.8617898  0.59559104 0.19051591 0.3976506  0.83056968 0.13047346
  0.49802828 0.11972894 0.8896605  0.2060293 ]
 [0.68507422 0.16738938 0.57424864 0.84203492 0.39972481 0.93592162
  0.8705719  0.15569782 0.20742975 0.99869984]
 [0.150475   0.14069176 0.19186455 0.25038375 0.06229889 0.75764862
  0.21640502 0.0828941  0.15363122 0.41918985]
 [0.99530439 0.74179615 0.561328   0.3250054  0.70559486 0.94791196
  0.2295923  0.87862503 0.68072817 0.26595356]
 [0.20210003 0.23820744 0.32808492 0.40597585 0.35014252 0.03089757
  0.54522308 0.10875479 0.32249552 0.31108518]
 [0.79142032 0.51989228 0.83285102 0.96291976 0.24300146 0.30933507
  0.59739574 0.56179853 0.23272956 0.25841003]
 [0.91351633 0.74314739 0.14801572 0.39183858 0.41460325 0.23266347
  0.26372056 0.74355893 0.49796168 0.44476284]
 [0.40980957 0.240439   0.26461374 0.90640266 0.2429123  0.89775432
  0.82192984 0.80780544 0.95006168 0.47784281]
 [0.88927682 0.05586622 0.99392915 0.6332094  0.24429021 0.562014
  0.55544972 0

14. Create a random vector of size 30 and find the mean value

In [9]:
ran_vec = np.random.random(30)
print(ran_vec.mean())

0.5398858180327323


15. Create a 2d array with 1 on the border and 0 inside 

In [3]:
d_arr = np.ones((5,5))
d_arr[1:-1,1:-1] = 0
print(d_arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


16. How to add a border (filled with 0's) around an existing array?

In [4]:
vector = np.ones((5,5))
vector = np.pad(vector, pad_width=1, mode='constant', constant_values=0)
print(vector)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

In [5]:
arr = np.diag(1+np.arange(4),k=-1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [ ]:
arr = np.zeros((8,8),dtype=int)
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [8]:
arr = np.unravel_index(100,(6,7,8))
print(arr)

(np.int64(1), np.int64(5), np.int64(4))



21. Create a checkerboard 8x8 matrix using the tile function

In [3]:
arr = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


22. Normalize a 5x5 random matrix

In [4]:
arr = np.random.random((5,5))
print(arr)
arr = (arr - arr.mean()) / (arr.std())
print(arr)

[[0.52250575 0.59624146 0.36215333 0.25724162 0.59481631]
 [0.03301906 0.40409878 0.20652402 0.41957539 0.30494984]
 [0.30279198 0.86298186 0.82511355 0.10774172 0.19103123]
 [0.59336191 0.5971444  0.87174149 0.03476386 0.29195312]
 [0.04047997 0.61260538 0.09552447 0.99524261 0.69614427]]
[[ 0.32085641  0.58456206 -0.25262195 -0.62782426  0.57946521]
 [-1.42972543 -0.10260984 -0.80920881 -0.04725986 -0.45720238]
 [-0.46491966  1.53852241  1.40309161 -1.16249009 -0.86461664]
 [ 0.57426374  0.5877913   1.56985002 -1.42348538 -0.50368337]
 [-1.40304252  0.64308534 -1.20618342  2.01153479  0.94185071]]


23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [5]:
arr = np.dtype([("r",np.ubyte,1),("g",np.ubyte,1),("b",np.ubyte,1),("a",np.ubyte,1)])
print(arr)

[('r', 'u1', (1,)), ('g', 'u1', (1,)), ('b', 'u1', (1,)), ('a', 'u1', (1,))]



24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [6]:
arr = np.dot(np.ones((5,3)), np.ones((3,2)))
print(arr)


[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [7]:
vector = np.arange(4)
print(vector)
vector += 5
print(vector)

[0 1 2 3]
[5 6 7 8]
